// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://voybocbmlhavtyckpucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZveWJvY2JtbGhhdnR5Y2twdWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTIzNjAsImV4cCI6MjA3MDE4ODM2MH0.wFpHfq8p-GbU3aLclS3CdEkL1R99G5KvFjOQybzp51Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});